server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          #uri: https://github.com/eemeliristikartano/spring-config-electricity-price
          uri: https://github.com/eemeliristikartano/Microservice-electricity-price-application
          search-paths: spring-config-electricity-price/price*
          username: ${username}
          password: ${password}

